"""purchase table changed

Revision ID: e70368f82b4b
Revises: 254f570af319
Create Date: 2025-10-20 13:20:13.530263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70368f82b4b'
down_revision: Union[str, Sequence[str], None] = '254f570af319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('product_section_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('purchase_racksection_id_fkey'), 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'product_section', ['product_section_id'], ['id'])
    op.drop_column('purchase', 'racksection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('racksection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_racksection_id_fkey'), 'purchase', 'racksection', ['racksection_id'], ['id'])
    op.drop_column('purchase', 'product_section_id')
    # ### end Alembic commands ###
